### ISSUE TITLE
ModuleNotFoundError: No module named 'rasa_core'

### ISSUE THREAD

**Issue by RonanBoyd** [dtaivpp/python-chatbot#2]
Hi there,

I am using a virtual environment in python 3.6.5.
When I run the command 'python train_init.py' I get the error:

Traceback (most recent call last):
  File "train_init.py", line 7, in <module>
    from rasa_core.agent import Agent
ModuleNotFoundError: No module named 'rasa_core'

I have tried using sudo, and python 3. Any ideas? I followed all your instructions to a T, including using pip 9.0.3. Something that might be of interest is that when I run 'python -m rasa_nlu.train -c config_spacy.json -d data/data.json -o models --path projects' I get this response:

INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
INFO:rasa_nlu.converters:Training data format at data/data.json is rasa_nlu
INFO:rasa_nlu.training_data:Training data stats: 
	- intent examples: 73 (9 distinct intents)
	- found intents: 'ask_name', 'chat_name', 'false_', 'give_banner', 'goodbye', 'greet', 'identity', 'system_name', 'true_'
	- entity examples: 14 (1 distinct entities)
	- found entities: 'bannerid'

INFO:rasa_nlu.model:Starting to train component nlp_spacy
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component tokenizer_spacy
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component intent_featurizer_spacy
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component intent_entity_featurizer_regex
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component ner_crf
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component ner_synonyms
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component intent_classifier_sklearn
Fitting 2 folds for each of 6 candidates, totalling 12 fits
/home/ronan/Documents/asixtwo/a-env/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/ronan/Documents/asixtwo/a-env/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/ronan/Documents/asixtwo/a-env/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/ronan/Documents/asixtwo/a-env/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/ronan/Documents/asixtwo/a-env/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/ronan/Documents/asixtwo/a-env/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.1s finished
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Successfully saved model into '/home/ronan/Documents/asixtwo/a-env/python-chatbot/projects/default/model_20180807-180954'
INFO:__main__:Finished training

Thanks alot for this upload though, it is more helpful than the other ones.
    -Ronan

**Comment by dtaivpp** [comment]
Hey Ronan, 

Run `pip install rasa_core` seems I left the core out of the requirementst.txt
Let me know if that ends up fixing it for you. Also, thank you! I am updating today to give a more streamlined process for configuring. Hopefully, that should be up by 5 pm on 8/8 (utc -5)

Cheers,
-Dave

**Comment by RonanBoyd** [comment]
Hi Dave, 

Thanks for getting back to me! Now it says no module named rasa_core.agent. I think I will wait until you update and try again!

-Ronan

**Comment by dtaivpp** [comment]
@RonanBoyd I just pushed a big change to the requirements, refactored a lot of code, removed duplicated code, and restructured the example. Try running using the instructions again and let me know if you have errors still.

edit* If you were working off of a clone of this I would delete and do a fresh clone. I added so many breaking changes merging would be nearly impossible.

Cheers, 
-Dave

**Comment by RonanBoyd** [comment]
i restarted, everything worked until i tried "python train_rasa_core.py"

it gave me the error 

Traceback (most recent call last):
  File "train_rasa_core.py", line 7, in <module>
    from rasa_core.agent import Agent
ImportError: No module named rasa_core.agent

Any ideas?

**Comment by dtaivpp** [comment]
Hey Ronan, 

After looking into it a bit more it seems that although we installed Rasa_Core it may not be in your path. I would try running the following to see if it helps `sudo pip3 install virtualenv --upgrade` (using pip 3 here but you may have pip already mapped to pip3)

Also, which operating system is your virtual environment running? I am working on updating the docs for Linux and can do and early merge. Just let me know your operating system and version you are running on.

**Comment by RonanBoyd** [comment]
Hey Dave,

i tried the virtualenv upgrade, no change to the error message. I then tried running "pip install rasa_core" and did the same for rasa_nlu, and then reinstalled the requirements.txt, and still the error message is the same.

I am using Xubuntu 18.04

**Comment by dtaivpp** [comment]
Okay I am going to try spinning up an xubuntu environment to see if I can replicate

**Comment by RonanBoyd** [comment]
by the way, to get that error message i had to write "sudo python train_rasa_core.py". otherwise it would say illegal instruction, core dumped

**Comment by dtaivpp** [comment]
Closing as fixed with commit 37f958f. Try the new instruction guide that I have posted labeled as "Installation on Linux" I found there were some issues with python3 not being used along with a versioning issue with the rasa_nlu. The instructions on there were exactly how I ran it on Xubuntu and was able to get it working. Only thing I did not put in there was `sudo apt install python3-pip` which will install pip3 for use in the tutorial. 

Let me know if you get any other errors and we can reopen. 

Cheers, 
-Dave

**Comment by RonanBoyd** [comment]
It still doesn't work.. if it worked for you i guess i should try re-installing my OS.

**Comment by dtaivpp** [comment]
That may be a good option. I am creating a docker container as well this upcoming week which may better allow you to run it.

**Comment by dtaivpp** [comment]
@RonanBoyd  I would also ensure you have run the following commands before trying to install on a fresh os. 

`sudo apt install python3`  
`sudo apt install python3-pip`  

That will ensure you are running the right python and pip versions. Then go through the linux install guide I posted. It says tested on Ubuntu but I also verified that it works on XUbuntu 18.04 as well the other day.

**Comment by RonanBoyd** [comment]
I still cant get it working. I will write exactly what I'm doing here.

cd ~/Documents
mkdir rasa
cd rasa
python3 -m venv rasa-env
cd rasa-env
source bin/activate
git clone [your link]
cd python-chatbot
sudo pip3 install -r requirements.txt
sudo python3 -m spacy download en_core_web_md
sudo python3 -m spacy link en_core_web_md en -f
python3 train_nlu.py

And when I run python3 train_nlu.py, I get the error "Illegal Instruction (core dumped)
If I run sudo python3 train_nlu.py, I get the error

Traceback (most recent call last):
  File "train_nlu.py", line 1, in <module>
    from rasa_nlu.training_data import load_data
ImportError: No module named rasa_nlu.training_data

I have tried all of your suggestions, re-installing Xubuntu, and everything I can think of. The program just doesn't want to work for me.

**Comment by dtaivpp** [comment]
@RonanBoyd I have found where your testing and mine have diverged. When you said you were working with python and a virtual environment I interpreted that as you were running a virtual machine with XUbuntu and not as you were running a python virtual environment. 

I am going back and testing with the python venv package to see if I can replicate.

**Comment by RonanBoyd** [comment]
Okay great, I also just installed a virtual machine running Kubuntu, on my windows machine. I haven't had time to test it yet but I will try to get everything running on that tonight and see if it was just some underlying issue with my laptop. Who knows.

**Comment by RonanBoyd** [comment]
@dtaivpp can we chat on discord? My tag is rbtzz#7092

**Comment by nezam1234** [comment]
hi ! 
i test rasa chatbot 
I need a database for folk conversations Please guide me where to download this dataset

**Comment by nezam1234** [comment]
Send me the data address(link) by email(karoo.majidy@gmail.com)
